name: docker sync

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to Amazon ECR Private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: "true"

      - name: sync
        uses: cloudposse/github-action-sync-docker-repos@initial-implementation
        with:
          src: busybox
          dest: 552533042161.dkr.ecr.us-east-1.amazonaws.com
          dest-credentials: "${{steps.login-ecr.outputs.docker_username_123456789012_dkr_ecr_aws_region_1_amazonaws_com}}:${{steps.login-ecr.outputsdocker_password_123456789012_dkr_ecr_aws_region_1_amazonaws_com}}"
