name: packer

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  test:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1
