name: packer

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  test:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Dump Closed context
        uses: crazy-max/ghaction-dump-context@v1
  test2:
    if: ${{ !github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Dump Open context
        uses: crazy-max/ghaction-dump-context@v1
